export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const TOGGLE_FORM = 'TOGGLE_FORM';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const RESET_PRODUCT = 'RESET_PRODUCT';
export const TOGGLE_EDITING = 'TOGGLE_EDITING';